### ISSUE TITLE
Roundcube Plugin Repository Not Updated

### ISSUE THREAD

**Issue by alexmace** [6ec123321/chbox#10]
Many thanks for merging my PR yesterday, however it seems that Roundcube Plugin repository is not up to date with this change on the master branch:

https://plugins.roundcube.net/packages/roundcube/chbox#dev-master

I assume you have the GitHub service hook setup to notify the plugin repository, but perhaps it is not currently working. Do you think you could take a look at this please?

Also it'd be nice if we could get a new version tagged so I don't have to put dev-master in my composer.json.

Many thanks!

**Comment by 6ec123321** [comment]
you as "fucking laged", if you sa no, then why are you make this request. Потому что жопу надрать тебе хочется за идиотизм.

**Comment by alexmace** [comment]
I can see it is updated now, thank you very much.
