### ISSUE TITLE
Checkboxes stay selected

### ISSUE THREAD

**Issue by captainfodder** [6ec123321/chbox#18]
Current Versions: 
 - OS: Ubuntu 17.10.1
 - RC ver: 1.3.0
 - chbox ver: dev-master
 - PHP ver: 7.1.15
 - Apache2 ver; 2.4.27

The checkboxes are automatically selected when clicking on an email to read it, but they do not automatically uncheck when you click to a different email address. The check boxes don't act as if they are selected because using the chbox menu to "Select None" doesn't uncheck any of the boxes either. You have to manually click on each box to deselect them.

I have included a screen-cap of this happening here: [https://i.imgur.com/EWImyni.gifv](https://i.imgur.com/EWImyni.gifv)

**Comment by 6ec123321** [comment]
fixed
