### ISSUE TITLE
Does it work with 1.1 version?

### ISSUE THREAD

**Issue by JonathanWH1** [6ec123321/chbox#4]

**Comment by 6ec123321** [comment]
Если можете, то протестируйте пожалуйста.

**Comment by 6ec123321** [comment]
Begin testing. I'll try to fix plugin for rundcube-1.1.0.

**Comment by JonathanWH1** [comment]
I did some work to make it work on 1.1. Interested?

**Comment by 6ec123321** [comment]
Yo, anderstand. Please, i need help with this problem. Do you have a skill with google browser in debuging.?

**Comment by 6ec123321** [comment]
I need as you for testing, because i'm mistakes some time when public a source code ))

**Comment by 6ec123321** [comment]
try this https://github.com/6ec123321/chbox/tree/roundcube-1.1.0-v0.2.3

Work with roundcubemail-1.1.0

Thank's

**Comment by 6ec123321** [comment]
https://github.com/6ec123321/chbox/archive/0.2.4.zip
23.03.2015 Fixed and Tested for Roundcubemail-1.0.3 and Roundcubemail-1.1.0

**Comment by JonathanWH1** [comment]
Hello Artur!

It's working as a charm! Thank you very much!



 Atenciosamente,


*Jonathan Araujo*

jonathan@wh1.com.br

+55 (31) 9139-5717


*WH1*

Cloud Computing

www.wh1.com.br






2015-03-20 6:24 GMT-03:00 Artur Petrov <notifications@github.com>:
